export default {
  LOAD_TASKS_SUCCESS: 'LOAD_TASKS_SUCCESS',
  LOAD_TASK_SUCCESS: 'LOAD_TASK_SUCCESS',
  LOAD_TASKS_FAIL: 'LOAD_TASKS_FAIL',
  ISLOADING: 'ISLOADING',
  UPDATETASKFILTER: 'UPDATETASKFILTER'
};
