export default {
  LOAD_TASKS_SUCCESS: 'LOAD_TASKS_SUCCESS',
  LOAD_TASK_SUCCESS: 'LOAD_TASK_SUCCESS',
  LOAD_TASKS_FAIL: 'LOAD_TASKS_FAIL',
  LOAD_UPDATE_SUCCESS: 'LOAD_UPDATE_SUCCESS',
  LOAD_UPDATE_FAIL: 'LOAD_UPDATE_FAIL',
  ISLOADING: 'ISLOADING',
  UPDATETASKFILTER: 'UPDATETASKFILTER',
  LOAD_TEAM_FAIL: 'LOAD_TEAM_FAIL',
  LOAD_TEAM_SUCCESS: 'LOAD_TEAM_SUCCESS'
};
